version: '3'

services:
    webserver:
        build: 
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - 8080:8080
        volumes:
            - ./rest:/usr/src/rest
            - ./tests:/usr/src/tests